# Generated by Django 3.1.2 on 2020-10-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogmod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=40)),
                ('blog_img', models.ImageField(upload_to='blogimage')),
                ('blog_img_max', models.ImageField(default='', upload_to='blogimage/blogmaximg')),
                ('blog_disc', models.TextField(max_length=1000)),
                ('blog_disc_max', models.TextField(default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='contactdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=300)),
                ('email', models.EmailField(default='', max_length=50)),
                ('phone', models.BigIntegerField()),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=30)),
                ('img_title', models.CharField(default='', max_length=40)),
                ('img_disc', models.TextField(default='', max_length=500)),
                ('img_src', models.ImageField(upload_to='gallerypics')),
                ('img_src_max', models.ImageField(default='', upload_to='gallerypics/gallerypicsmax')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=300)),
                ('pub_date', models.DateField()),
                ('img', models.ImageField(default='', upload_to='productimg')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
