# Generated by Django 3.1.2 on 2020-10-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_img', models.ImageField(upload_to='productimg')),
                ('product_desc', models.TextField()),
                ('product_pdate', models.DateField()),
            ],
        ),
    ]
