# Generated by Django 3.1.2 on 2020-10-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shopproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=50)),
                ('cust_email', models.EmailField(max_length=254)),
                ('cust_phone', models.BigIntegerField()),
                ('cust_address', models.CharField(max_length=500)),
                ('cust_city', models.CharField(max_length=200)),
                ('cust_state', models.CharField(max_length=200)),
                ('cust_zip_code', models.BigIntegerField()),
                ('order_payment_type', models.CharField(max_length=50)),
                ('order_payment_status', models.CharField(max_length=200)),
                ('order_status', models.CharField(max_length=200)),
                ('order_item_num', models.IntegerField()),
                ('order_grand_total', models.FloatField()),
            ],
        ),
    ]
