# Generated by Django 3.1.2 on 2020-10-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderiteminfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('order_item_name', models.CharField(max_length=50)),
                ('order_item_qty', models.IntegerField()),
                ('order_item_price', models.FloatField()),
                ('order_item_total_price', models.FloatField()),
            ],
        ),
    ]
